services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app 
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DB=mydatabase
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - node_modules_vol:/app/node_modules
    ports:
      - 3000:3000 
    environment:
      - CHOKIDAR_USEPOLLING=true
  db:
    image: mysql:latest
    build: ./mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: eatsnapDB
      TZ: 'Asia/Tokyo'
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d # ホストのディレクトリをコンテナ内にマウント
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379

volumes:
  db-store:
  node_modules_vol: {}


